In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [4]:
# create a model class that inherits nn.Module

class Model(nn.Module):

    # Input layer (4 features) -> hidden layer1 (number of neurons) -> hidden layer2 etc
    # output to 3 potential classes

    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        super().__init__() # insantiate nn.module
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)

        return x

In [5]:
torch.manual_seed(41)

model = Model()

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)

In [9]:
my_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
print(my_df.groupby('species').max())

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [ ]:
#change last column from strings to integers
my_df['species'] = my_df['species'].replace('setosa', 0.0)
my_df['species'] = my_df['species'].replace('versicolor', 1.0)
my_df['species'] = my_df['species'].replace('virginica', 2.0)
my_df

     sepal_length  sepal_width  petal_length  petal_width species
0             5.1          3.5           1.4          0.2     0.0
1             4.9          3.0           1.4          0.2     0.0
2             4.7          3.2           1.3          0.2     0.0
3             4.6          3.1           1.5          0.2     0.0
4             5.0          3.6           1.4          0.2     0.0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3     2.0
146           6.3          2.5           5.0          1.9     2.0
147           6.5          3.0           5.2          2.0     2.0
148           6.2          3.4           5.4          2.3     2.0
149           5.9          3.0           5.1          1.8     2.0

[150 rows x 5 columns]

In [25]:
# Train test split

X = my_df.drop('species', axis=1)
y = my_df['species']

In [ ]:
# convert them to np arrays

X = X.values
y = y.values

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
#train test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

In [ ]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)